# Zjazd 3, część 1 — NumPy
**Autor:** Zuzanna

In [31]:
import numpy as np

In [32]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [33]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [36]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [37]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [38]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [39]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [40]:
#1.Sprzedaż w styczniu (indeks 0):
print(miesiace_sprzedaz[0])

120


In [41]:
#2.Sprzedaż w grudniu (ostatni element):
print(miesiace_sprzedaz[-1])

221


In [42]:
#3.Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [43]:
#4.Sprzedaż w Q4 (październik-grudzień, ostatnie 3):
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [44]:
#5.Sprzedaż co drugi miesiąc (styczeń, marzec, maj...):
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [45]:
#6.Sprzedaż od tyłu (grudzień → styczeń):
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


Część B — Macierz 2D

In [46]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [47]:
#1.Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):
print(dane[0, 1])

145


In [48]:
#2.Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):
print(dane[2])

[234 267 289]


In [49]:
#3.Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):
print(dane[:, 0])

[120  89 234  56]


In [50]:
#4.Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


Ćwiczenie 3: Operacje wektorowe — analiza biznesowa 

In [51]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [52]:
#Zadanie 1: Podstawowe statystyki cenowe
# Średnia cena
print("Średnia cena:", ceny.mean())

# Najdroższy produkt
idx_max = ceny.argmax()
print("Najdroższy:", nazwy[idx_max], ceny[idx_max])

# Najtańszy produkt
idx_min = ceny.argmin()
print("Najtańszy:", nazwy[idx_min], ceny[idx_min])



Średnia cena: 1171.0
Najdroższy: Laptop 3499
Najtańszy: Ładowarka 89


In [53]:
#Zadanie 2: Wartość magazynu
# Wartość każdego produktu
wartosci = ceny * ilosci_magazyn

print("Wartość produktów:", wartosci)

# Łączna wartość magazynu
print("Łączna wartość magazynu:", wartosci.sum())

Wartość produktów: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465


In [54]:
#Zadanie 3: Analiza cenowa

# Rabat 15%
ceny_rabat = ceny * 0.85
print("Ceny po rabacie:", ceny_rabat)

# VAT 23%
ceny_vat = ceny * 1.23
print("Ceny z VAT:", ceny_vat)

# Ile produktów > 1000 zł
ile_drogich = (ceny > 1000).sum()
print("Produkty powyżej 1000 zł:", ile_drogich)

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Produkty powyżej 1000 zł: 4


In [57]:
#Zadanie 4: Filtrowanie
nazwy_np = np.array(nazwy)
# Produkty z oceną >= 4.5
maska = oceny_klientow >= 4.5
print("Produkty (>=4.5):", nazwy_np[maska])
print("Ceny:", ceny[maska])

# Produkty poniżej 200 zł
maska = ceny < 200
print("Produkty (<200 zł):", nazwy_np[maska])
print("Ilości:", ilosci_magazyn[maska])

Produkty (>=4.5): ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]
Produkty (<200 zł): ['Ładowarka' 'Mysz']
Ilości: [312 201]


In [58]:
#Zadanie 5: Analiza zapasów
# Produkty z niskim stanem (< 30)
maska = ilosci_magazyn < 30
print("Niski stan:", nazwy_np[maska])

# Wartość tych produktów
wartosci = ceny * ilosci_magazyn
print("Wartość niskiego stanu:", wartosci[maska].sum())

# Procent całego magazynu
procent = wartosci[maska].sum() / wartosci.sum() * 100
print("Procent magazynu:", procent)

Niski stan: ['Laptop' 'Monitor']
Wartość niskiego stanu: 86962
Procent magazynu: 15.826667758637946


In [59]:
#Zadanie 6 (bonus): Analiza korelacji cena–ocena
# Okazje (ocena >= 4.5 i cena < 1000)
maska = (oceny_klientow >= 4.5) & (ceny < 1000)
print("Okazje:", nazwy_np[maska])
print("Ceny:", ceny[maska])

# Średnia cena dla ocen 4.0–4.5
maska = (oceny_klientow >= 4.0) & (oceny_klientow < 4.5)
print("Średnia cena:", ceny[maska].mean())

Okazje: ['Słuchawki']
Ceny: [349]
Średnia cena: 759.0


Ćwiczenie 4: Benchmark — lista vs NumPy

In [60]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  39.3 ms
NumPy:  2.0 ms
NumPy jest 20× szybszy!


In [61]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  3.8 ms
NumPy:  0.8 ms
NumPy jest 5× szybszy!


In [62]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  27.2 ms
NumPy:  2.0 ms
NumPy jest 14× szybszy!


## Wnioski z benchmarku

- NumPy jest **X razy** szybszy w mnożeniu
- NumPy jest **X razy** szybszy w sumowaniu
- NumPy jest **X razy** szybszy w filtrowaniu
- Wniosek: przy dużych danych zawsze używaj NumPy zamiast listm