# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** Zuzanna Kurpińska

In [65]:
import numpy as np

In [66]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


Krok 2 — Zadania


In [67]:
#Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.
ceny_inflacja = ceny * 1.05
print(ceny_inflacja)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [68]:
#Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.
rabaty = np.array([0.10, 0.05, 0.15])
ceny_po_rabacie = ceny * (1 - rabaty)
print(ceny_po_rabacie)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [69]:
#Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%.
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt = ceny / (1 + marza)
print(koszt)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [70]:
#Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.
indeksy = ceny.argmin(axis=1)
sklepy_np = np.array(sklepy)
print(sklepy_np[indeksy])


['Online' 'Online' 'Online' 'Online']


Ćwiczenie 2: Reshape i łączenie danych

In [71]:
#Zadanie 2a — Reshape

dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

kwartaly = dane_flat.reshape(4, 3)

print("Kwartały:\n", kwartaly)

suma_kw = kwartaly.sum(axis=1)
print("Suma per kwartał:", suma_kw)

najlepszy = suma_kw.argmax() + 1
print("Najlepszy kwartał: Q", najlepszy)

Kwartały:
 [[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q 4


In [72]:
#Zadanie 2b — Stacking
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])

print("Wszystkie:\n", wszystkie)

print("Suma per oddział:", wszystkie.sum(axis=1))
print("Suma per kwartał:", wszystkie.sum(axis=0))

Wszystkie:
 [[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [73]:
#Zadanie 2c — Praktyczne
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

# 1. reshape 6x2
macierz = sprzedaz_flat.reshape(6, 2)

print("Macierz:\n", macierz)

# 2. średnia sprzedaż per produkt
srednia = macierz.mean(axis=1)
print("Średnia per produkt:", srednia)

# 3. zmiana między miesiącami
zmiana = macierz[:, 1] - macierz[:, 0]
print("Zmiana miesiąc 2 - 1:", zmiana)

Macierz:
 [[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia per produkt: [150. 225. 215. 170. 240. 225.]
Zmiana miesiąc 2 - 1: [100 150 -70 100 140 -70]


In [74]:
#Zadanie 2d — Flatten i concatenate
# zakładam że masz już kwartaly z zadania 2a

wektor = kwartaly.flatten()
print("Flatten:", wektor)

nowy = np.concatenate([wektor, np.array([235])])
print("Po dodaniu miesiąca:", nowy)
 

Flatten: [120 135  98 142 167 189 201 178 156 143 198 221]
Po dodaniu miesiąca: [120 135  98 142 167 189 201 178 156 143 198 221 235]


Ćwiczenie 3: Analiza danych finansowych

In [75]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [76]:
#Zadanie 3a: Analiza wynagrodzeń
# 1. statystyki
srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()

print("Średnia:", srednia)
print("Mediana:", mediana)
print("Odchylenie std:", odchylenie)


# 2. osoby powyżej średniej
pracownicy_np = np.array(pracownicy)
powyzej = pracownicy_np[pensje > srednia]

print("Powyżej średniej:", powyzej)


# 3. osoby poniżej mediany
ponizej = pracownicy_np[pensje < mediana]

print("Poniżej mediany:", ponizej)


# 4. rozstęp i IQR
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("Rozstęp:", rozstep)
print("IQR:", iqr)


Średnia: 6425.0
Mediana: 6050.0
Odchylenie std: 1616.9029037020127
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900
IQR: 2200.0


In [77]:
#Zadanie 3b: System premii (np.where)
# premie
premie = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

print("Premie:", premie)

# nowe wynagrodzenie
nowe_pensje = pensje + premie
print("Nowe pensje:", nowe_pensje)

# kto dostał największą premię
idx = premie.argmax()
print("Najwyższa premia:", pracownicy[idx])


Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższa premia: Ewa


In [78]:
#Zadanie 3c: Ranking (argsort);
kolejnosc = np.argsort(pensje)[::-1]

for i, idx in enumerate(kolejnosc, 1):
    print(i, pracownicy[idx], pensje[idx], staz[idx])

1 Marek 9100 15
2 Zofia 8500 12
3 Jan 7200 8
4 Kasia 6300 5
5 Tomek 5800 4
6 Anna 5500 3
7 Ewa 4800 2
8 Piotr 4200 1


In [79]:
#Zadanie 3d: Korelacja
# korelacje
korelacja_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
korelacja_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print("Staż vs pensja:", korelacja_staz_pensja)
print("Staż vs ocena:", korelacja_staz_ocena)

# który silniejszy
if abs(korelacja_staz_pensja) > abs(korelacja_staz_ocena):
    print("Silniejsza zależność: staż vs pensja")
else:
    print("Silniejsza zależność: staż vs ocena")

Staż vs pensja: 0.987862864584301
Staż vs ocena: 0.04198471605953068
Silniejsza zależność: staż vs pensja


In [80]:
#Zadanie 3e: Analiza sprzedaży (broadcasting)
# 1. poprawne dopasowanie wymiarów
ceny_kol = ceny_produktow.reshape(4, 1)

# 2. przychód (4 produkty × 6 miesięcy)
przychod = sprzedaz * ceny_kol

print("Przychód:\n", przychod)


# 3. który produkt zarobił najwięcej (sumujemy po miesiącach)
suma_produkt = przychod.sum(axis=1)
idx_prod = suma_produkt.argmax()
print("Najlepszy produkt:", produkty_nazwy[idx_prod])


# 4. który miesiąc był najlepszy (sumujemy po produktach)
suma_miesiac = przychod.sum(axis=0)
idx_mies = suma_miesiac.argmax()
print("Najlepszy miesiąc:", idx_mies + 1)


# 5. trend (pierwsze 3 vs ostatnie 3 miesiące)
pierwsze = przychod[:, :3].sum()
ostatnie = przychod[:, 3:].sum()

print("Pierwsze 3 mies:", pierwsze)
print("Ostatnie 3 mies:", ostatnie)

if ostatnie > pierwsze:
    print("Trend rosnący 📈")
else:
    print("Trend malejący 📉")


Przychód:
 [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Najlepszy produkt: Smartfon
Najlepszy miesiąc: 2
Pierwsze 3 mies: 2463950
Ostatnie 3 mies: 2536500
Trend rosnący 📈


Ćwiczenie 4: Generowanie danych

In [82]:
 #Krok 1 — Generowanie
import numpy as np

np.random.seed(42)

# wiek: normalny, średnia 35, std 10, min 18
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)

# wydatki: normalny, średnia 500, std 200, min 0
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)

# liczba wizyt: Poisson (lambda = 5)
wizyty = np.random.poisson(5, 100)

print("Wiek:", wiek[:5])
print("Wydatki:", wydatki[:5])
print("Wizyty:", wizyty[:5])

Wiek: [39 33 41 50 32]
Wydatki: [216.92585159 415.87093545 431.45709669 339.54454616 467.74285767]
Wizyty: [11  7  3  2  3]


In [83]:
#Krok 2 — Analiza
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
print(f"Wiek → średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")
print(f"Wydatki → średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")
print(f"Wizyty → średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")


# 2. Korelacja wiek vs wydatki
print("Korelacja wiek vs wydatki:", np.corrcoef(wiek, wydatki)[0, 1])


# 3. Korelacja wizyty vs wydatki
print("Korelacja wizyty vs wydatki:", np.corrcoef(wizyty, wydatki)[0, 1])


# 4. Segmentacja klientów za pomocą np.where
sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(wydatki > sr + sd, 'WYSOKI',
          np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

print("Segmenty:", segment)


# 5. Ile klientów w każdym segmencie (np.unique)
unikalne, liczby = np.unique(segment, return_counts=True)

for s, l in zip(unikalne, liczby):
    print(s, ":", l)

Wiek → średnia: 33.6, mediana: 33.0, std: 8.6, min: 18, max: 53
Wydatki → średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty → średnia: 4.9, mediana: 5.0, std: 2.2, min: 1, max: 11
Korelacja wiek vs wydatki: -0.12009183441777695
Korelacja wizyty vs wydatki: -0.15884985147948125
Segmenty: ['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI'
 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'NISKI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'WYSOKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDN